### ISSUE TITLE
报错 非200状态响应

### ISSUE THREAD

**Issue by dengdizzy** [cyanray/cx-auto-sign#21]
` at CxSignHelper.CxSignClient.GetCoursesAsync() in F:\Project\cx-auto-sign\CxSignHelper\CxSignClient.cs:line 155
   at cx_auto_sign.InitCommand.OnExecuteAsync(CommandLineApplication app) in F:\Project\cx-auto-sign\cx-auto-sign\InitCommand.cs:line 51`

**Comment by cyanray** [comment]
多试几次，每次都是这样吗

另外还需要检查你的电脑/服务器能不能打开超星网 [http://i.mooc.chaoxing.com/space/index](http://i.mooc.chaoxing.com/space/index)

**Comment by dengdizzy** [comment]
@cyanray 每次都是这样，但是我在另一台电脑上可以正常运行。以及在报错的电脑上继续执行自动签到而非初始化登录时，powershell显示的内容与正常运行的powershell显示内容一样。

**Comment by cyanray** [comment]
> @cyanray 每次都是这样，但是我在另一台电脑上可以正常运行。以及在报错的电脑上继续执行自动签到而非初始化登录时，powershell显示的内容与正常运行的powershell显示内容一样。

我这里无法复现这个错误。如果在另一台电脑上可以正常运行，这个错误可能和学校、账号无关，应该只是网络环境导致的错误。

在可以正常运行的电脑上执行init指令后，将整个程序以及生成的所有文件都复制到报错的电脑。
这样在报错的电脑上执行work指令才是有用的。
Courses目录下一个文件对应一门课程。init指令执行失败，Courses目录下没有文件，work指令是不会进行签到的。
