### ISSUE TITLE
使用时遇到的问题

### ISSUE THREAD

**Issue by uniStark** [cyanray/cx-auto-sign#22]
在输入 .\cx-auto-sign.exe init -u "userName" -p "userPassword"时报错：
.\cx-auto-sign.exe : 无法将“.\cx-auto-sign.exe”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，
如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ .\cx-auto-sign.exe init -u "userName" -p "userPassword"
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\cx-auto-sign.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

![image](https://user-images.githubusercontent.com/38497714/99929385-0786a980-2d88-11eb-95e2-8d7377c8dbcf.png)

**Comment by cyanray** [comment]
请检查cx-auto-sign.exe和cx-auto-sign.dll是否存在于当前目录
或者这样使用： `dotnet cx-auto-sign.dll`
