### ISSUE TITLE
关于邮箱以及是否支持server酱的一些问题

### ISSUE THREAD

**Issue by nidajia** [cyanray/cx-auto-sign#25]
你好，我想用qq邮箱但是配置不成功，以及能否支持server酱呢

**Comment by cyanray** [comment]
我一直使用邮箱通知，没有问题。
qq邮箱默认不开启smtp服务，请检查是否已经开通smtp服务。

server酱会考虑支持

**Comment by cyanray** [comment]
已经支持ServerChan通知
