### ISSUE TITLE
支持使用server酱推送签到通知

### ISSUE THREAD

**Issue by cyanray** [cyanray/cx-auto-sign#26]
// http://sc.ftqq.com/3.version

配置比邮箱简单

**Comment by Lytsu** [comment]
您好，具体应该如何实现呢，是需要自行编译么？

**Comment by cyanray** [comment]
> 您好，具体应该如何实现呢，是需要自行编译么？

还没有实现，下一个版本会支持的。

**Comment by cyanray** [comment]
已经支持ServerChan通知
