### ISSUE TITLE
初始化无法下载课程数据.

### ISSUE THREAD

**Issue by xiaoicx** [cyanray/cx-auto-sign#31]
初始化无法下载课程数据 望作者有时间修复一下
![image](https://user-images.githubusercontent.com/29257919/109416687-b9261e00-79fa-11eb-8ee9-c3cf50b5193a.png)

**Comment by cyanray** [comment]
超星API返回内容有变化，导致正则表达式失效。

**Comment by cyanray** [comment]
可以到 https://github.com/cyanray/cx-auto-sign/actions/runs/609517393 下方 Artifacts 处下载修复版(cx-auto-sign-publish)，暂时没时间发新版。

**Comment by xiaoicx** [comment]
> 可以到 https://github.com/cyanray/cx-auto-sign/actions/runs/609517393 下方 Artifacts 处下载修复版(cx-auto-sign-publish)，暂时没时间发新版。

好的已下载正在使用,感谢作者的修复.
