### ISSUE TITLE
关掉shell软件后就无法进行签到

### ISSUE THREAD

**Issue by aa1052** [cyanray/cx-auto-sign#37]
![22](https://user-images.githubusercontent.com/74482577/114995200-25d47980-9ed0-11eb-841c-6ecd874cd6e7.png)
大佬，我把这个软件关掉后，就没法签到了，为啥啊，

**Comment by aa1052** [comment]
用的centos8,腾讯云

**Comment by cyanray** [comment]
这是 Linux 的操作问题，可以百度以下关键词：“linux 关闭终端 继续运行程序” 、“nohup”、 “screen” 了解如何解决。
