### ISSUE TITLE
签到位置不准确

### ISSUE THREAD

**Issue by ericting** [cyanray/cx-auto-sign#38]
如题，设置的经纬度和签到后，学习通里边签到成功的经纬度不同（偏移了）

**Comment by cyanray** [comment]
程序将设置的经纬度直接提交给签到接口，不存在精度损失导致的误差。
只可能是经纬度设置错误，建议你抓包cx，获取正确的经纬度。

**Comment by ericting** [comment]
好的，不过我一点点改经纬度参数已经可以了，改成了签到的位置在教室

**Comment by moeshin** [comment]
有种东西叫做坐标加密，手机指南针出来坐标和地图上的坐标是有偏差的。

超星使用的是百度地图，网上有在线工具 https://tool.lu/coordinate/
