### ISSUE TITLE
后面添加的课程不会签到

### ISSUE THREAD

**Issue by moeshin** [cyanray/cx-auto-sign#39]
需要重新初始化？白给 :joy:

**Comment by cyanray** [comment]
这是肯定的，不然误签到新课程更加麻烦。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年7月6日 11:30
收件人: ***@***.***>
抄送: ***@***.***>
主题: [cyanray/cx-auto-sign] 后面添加的课程不会签到 (#39)


需要重新初始化？白给 😂

**Comment by cyanray** [comment]
这是肯定的，不然误签到新课程更加麻烦。

**Comment by moeshin** [comment]
那在文档标注一下 😂
搞个 update 命令， 从 `AppConfig.json` 读取账号，更新课程？

**Comment by cyanray** [comment]
> 那在文档标注一下 😂
> 搞个 update 命令， 从 `AppConfig.json` 读取账号，更新课程？

近段时间比较忙，如果可以pr帮忙标注一下就更好了。
update指令会考虑的，这个功能可能需要一个json文件记录被删除的课程。

**Comment by moeshin** [comment]
所有课程为什么不整成一个文件呢？课程多一个个打开看也麻烦。
然后，在课程里写是否签到，再格式一下 JSON 看起来也舒服很多。
比如，自定义空间大：
```json5
{
  "Default": {
    "Enable": false, // 签到总开关
    "Normal": true, // 普通签到
    "Gesture": true, // 手势签到
    "Image": "", // 图片签到，图片名，null 不启用，内容为空则使用默认图片
    "QR": null, // 二维码签到，二维码 enc 值，null 不启用
    "Location": // 定位签到，null 不启用
    {
      "Address": "中国", // 定位签到的中文名地址
      "Latitude": "-1", // 定位签到的纬度
        "Longitude": "-1", // 定位签到的经度
        "ClientIp": "1.1.1.1", // 签到时提交的客户端ip地址
    },
    "DelaySeconds": 10, // 检测到新签到活动后延迟签到的秒数（过小容易出现秒签到现象）
  },
  "012345678-0123456": {
    "CourseId": 012345678,
    "ClassId": 0123456,
    "ChatId": 01234567890123,
    "CourseName": "课程名",
    "ClassName": "班级名",
    "Sign": // 课程里如果没有的项，则使用默认 Default 里的设置
    {
      "Enable": true, // 签到总开关
      // "Normal": true, // 普通签到
      // "Gesture": true, // 手势签到
      // "Image": "", // 图片签到，图片名，null 不启用，内容为空则使用默认图片
      // "QR": null, // 二维码签到，二维码 enc 值，null 不启用
      // "Location": // 定位签到，null 不启用
      // {
      //   "Address": "中国", // 定位签到的中文名地址
      //   "Latitude": "-1", // 定位签到的纬度
      //     "Longitude": "-1", // 定位签到的经度
      //     "ClientIp": "1.1.1.1", // 签到时提交的客户端ip地址
      // },
      // "DelaySeconds": 10, // 检测到新签到活动后延迟签到的秒数（过小容易出现秒签到现象）
    }
  }
}
```
我蒟蒻，没写 C#

**Comment by cyanray** [comment]
> 所有课程为什么不整成一个文件呢？课程多一个个打开看也麻烦。
> 然后，在课程里写是否签到，再格式一下 JSON 看起来也舒服很多。
> 比如，自定义空间大：
> 
> ```js
> {
>   "Default": {
>     "Enable": false, // 签到总开关
>     "Normal": true, // 普通签到
>     "Gesture": true, // 手势签到
>     "Image": "", // 图片签到，图片名，null 不启用，内容为空则使用默认图片
>     "QR": null, // 二维码签到，二维码 enc 值，null 不启用
>     "Location": // 定位签到，null 不启用
>     {
>       "Address": "中国", // 定位签到的中文名地址
>       "Latitude": "-1", // 定位签到的纬度
>         "Longitude": "-1", // 定位签到的经度
>         "ClientIp": "1.1.1.1", // 签到时提交的客户端ip地址
>     },
>     "DelaySeconds": 10, // 检测到新签到活动后延迟签到的秒数（过小容易出现秒签到现象）
>   },
>   "012345678-0123456": {
>     "CourseId": 012345678,
>     "ClassId": 0123456,
>     "ChatId": 01234567890123,
>     "CourseName": "课程名",
>     "ClassName": "班级名",
>     "Sign": // 课程里如果没有的项，则使用默认 Default 里的设置
>     {
>       "Enable": true, // 签到总开关
>       // "Normal": true, // 普通签到
>       // "Gesture": true, // 手势签到
>       // "Image": "", // 图片签到，图片名，null 不启用，内容为空则使用默认图片
>       // "QR": null, // 二维码签到，二维码 enc 值，null 不启用
>       // "Location": // 定位签到，null 不启用
>       // {
>       //   "Address": "中国", // 定位签到的中文名地址
>       //   "Latitude": "-1", // 定位签到的纬度
>       //     "Longitude": "-1", // 定位签到的经度
>       //     "ClientIp": "1.1.1.1", // 签到时提交的客户端ip地址
>       // },
>       // "DelaySeconds": 10, // 检测到新签到活动后延迟签到的秒数（过小容易出现秒签到现象）
>     }
>   }
> }
> ```
> 
> 我蒟蒻，没写 C#

我课程太多了，二十多门课，放一个文件里反而不方便（文件内容很长，删除内容要先选中再delete），我大多数课程都不签到，要被删掉的。
init指令执行结果里会输出 id-课程名称 的列表，根据这个输出信息来删文件就不用一个一个打开看。

根据课程进行设置可以考虑支持，但是我已经毕业了，可能没法进行测试。

**Comment by cyanray** [comment]
#40 #41

**Comment by moeshin** [comment]
我 fork 一份大改自用测试中

**Comment by cyanray** [comment]
> 我 fork 一份大改自用测试中

写的真好呜呜呜呜，欢迎测试后提交PR🤞
