### ISSUE TITLE
您已经分析im系统了，请问可不可以制作超星自己给自己发消息，想给超星做个bot

### ISSUE THREAD

**Issue by Closty** [cyanray/cx-auto-sign#43]

**Comment by cyanray** [comment]
我只做了登录认证部分的协议，其他部分的协议并没有做。
你可以根据[我博客的这篇文章](https://uint128.com/2020/11/16/%E8%B6%85%E6%98%9F%E5%AD%A6%E4%B9%A0%E9%80%9AIM%E5%8D%8F%E8%AE%AE%E5%88%86%E6%9E%90/)完成其余部分。

超星的IM其实就是环信IM提供的服务，你可以从他们的网站下载SDK。因为他们没提供.NET的SDK，所以我才自己解析的。
