### ISSUE TITLE
Could not execute because the application was not found or a compatible .NET SDK is not installed.

### ISSUE THREAD

**Issue by BrightMoonInner** [cyanray/cx-auto-sign#44]
我已经安装好了.NET5，为什么会这样呢：

Could not execute because the application was not found or a compatible .NET SDK
 is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application './cx-auto-sign.dll' does not exist.
  * You intended to execute a .NET SDK command:
      A compatible installed .NET SDK for global.json version [5.0.100] from [D:
\Users\Desktop\cx-auto-sign-master\global.json] was not found.
      Install the [5.0.100] .NET SDK or update [D:\Users\Desktop\cx-auto-sign-ma
ster\global.json] with an installed .NET SDK:
        5.0.301 [C:\Program Files\dotnet\sdk]

好奇怪啊，麻烦大佬给看看了，谢谢♪(･ω･)ﾉ

**Comment by cyanray** [comment]
我也不懂

**Comment by BrightMoonInner** [comment]
> 
> 
> 我也不懂，如果你无法解决这个问题，那么说明你不是本程序的目标用户。本开源项目是为了避免有能力开发相同软件的人重复工作，而不是提供软件帮你们逃课的。

没有，只是有时候可能会忘记

**Comment by moeshin** [comment]
如果想直接运行，应该去 Releases 或 Actions 下载编译好的，而不是下载这个项目

这一点 README 文档中是有写的

------

如果是想要自己编译，可能是 `global.json` 的问题

当初我是直接改成本地版本 https://github.com/cyanray/cx-auto-sign/blob/afcc484e8f2aec206fc79b766e3c335a6555ffba/global.json#L3

现在应该不会有这个问题了 https://github.com/cyanray/cx-auto-sign/commit/37ef741307fb26f40a5e586eb4dbcff2e8f31e74

——来自不懂 C# 网友的  ![胡乱分析](https://user-images.githubusercontent.com/28248888/134240554-76410a51-0490-40ce-8c77-3500aa2824a4.jpg)

**Comment by cyanray** [comment]
> > 我也不懂，如果你无法解决这个问题，那么说明你不是本程序的目标用户。本开源项目是为了避免有能力开发相同软件的人重复工作，而不是提供软件帮你们逃课的。
> 
> 没有，只是有时候可能会忘记。话说这大佬讲话怎么一股公知味……今日方信“有些学计算机学得好的同学，学着学着已经丧失人性了”非虚言也。

你怎么看不重要，这就是我筛选用户的方式，不阻止滥用只会让所有人都无法用。

**Comment by BrightMoonInner** [comment]
> > > 我也不懂，如果你无法解决这个问题，那么说明你不是本程序的目标用户。本开源项目是为了避免有能力开发相同软件的人重复工作，而不是提供软件帮你们逃课的。
> > 
> > 
> > 没有，只是有时候可能会忘记。话说这大佬讲话怎么一股公知味……今日方信“有些学计算机学得好的同学，学着学着已经丧失人性了”非虚言也。
> 
> 你怎么看不重要，这就是我筛选用户的方式，不阻止滥用只会让所有人都无法用。

不用激动，我只是指出你之前回复我的那段话莫名其妙、逻辑混乱，攻击性还挺强。
如果你只说一句你不是很清楚，我倒是觉得很合理，很可以理解。但接下来几句，我觉得就很离谱。我过来请教系铃人，你怎么说“如果你无法解决这个问题”？如果我自己就顺利解决了，那我还用过来提issue吗？如果是钱没有到位，你提供的服务收费，那我觉得在一定范围内也都能接受。假如你说“你得请我喝杯奶茶”，都比你上面那么说好……我不是付费咨询，你不帮助解决当然没有问题，推诿搪塞则完全没有必要，不需要的，谢谢。“不是目标用户”这话可就太万能了，只要使用了你的这些脚本遭遇了问题，你都可以说不是你的目标用户，最后目标用户可以缩至自己一人。“开发相同软件”，开发出来之后按照既定使用方案去使用它都用不了，那这开发有什么意义。我一步一步按照你的使用指导操作，最后出现了那样的错误，你的开发是存在问题的吧。我也没有攻击你代码不行。最后逃课这话就更离谱了，好家伙，我直呼好家伙，你明明只能推断出我是你这脚本的一个使用者，其它方面信息都是不足的，你根本不认识我，不知道我是什么人，使用这脚本是派啥用场，你却就直接认定我是逃课的。还有一点需要指正，签到和上课根本就是两回事，你也不要太把签到当回事了。我去上了课但可能没想起签到，我签了到却没有去上课，都是可以存在的情况，这两件事情互相之间本来既不充分也不必要，你自信按照充要进一步演绎出结论。我觉得一个计算机行业的人是这种逻辑能力水平，真是很让人吃惊的。总而言之，你对我的issue说了一些让人匪夷所思的话，想不明白你为什么突然攻击一个素不相识的人。可能你平时现实生活中就是这么说话的，那我当然无权干涉。我怎么看当然不重要，你怎么看也不重要，个人的看法都很微小，都没什么意义。筛选，那自然是双向筛选了。滥用，那就很高估我了，这脚本我根本都用不了，还滥用呢。打扰你开发，我非常抱歉，那你现在可以拉黑我了。

**Comment by cyanray** [comment]
> > > > 我也不懂，如果你无法解决这个问题，那么说明你不是本程序的目标用户。本开源项目是为了避免有能力开发相同软件的人重复工作，而不是提供软件帮你们逃课的。
> > > 
> > > 
> > > 没有，只是有时候可能会忘记。话说这大佬讲话怎么一股公知味……今日方信“有些学计算机学得好的同学，学着学着已经丧失人性了”非虚言也。
> > 
> > 
> > 你怎么看不重要，这就是我筛选用户的方式，不阻止滥用只会让所有人都无法用。
> 
> 不用激动，我只是指出你之前回复我的那段话莫名其妙、逻辑混乱，攻击性还挺强。 如果你只说一句你不是很清楚，我倒是觉得很合理，很可以理解。但接下来几句，我觉得就很离谱。我过来请教系铃人，你怎么说“如果你无法解决这个问题”？如果我自己就顺利解决了，那我还用过来提issue吗？如果是钱没有到位，你提供的服务收费，那我觉得在一定范围内也都能接受。假如你说“你得请我喝杯奶茶”，都比你上面那么说好……我不是付费咨询，你不帮助解决当然没有问题，推诿搪塞则完全没有必要，不需要的，谢谢。“不是目标用户”这话可就太万能了，只要使用了你的这些脚本遭遇了问题，你都可以说不是你的目标用户，最后目标用户可以缩至自己一人。“开发相同软件”，开发出来之后按照既定使用方案去使用它都用不了，那这开发有什么意义。我一步一步按照你的使用指导操作，最后出现了那样的错误，你的开发是存在问题的吧。我也没有攻击你代码不行。最后逃课这话就更离谱了，好家伙，我直呼好家伙，你明明只能推断出我是你这脚本的一个使用者，其它方面信息都是不足的，你根本不认识我，不知道我是什么人，使用这脚本是派啥用场，你却就直接认定我是逃课的。还有一点需要指正，签到和上课根本就是两回事，你也不要太把签到当回事了。我去上了课但可能没想起签到，我签了到却没有去上课，都是可以存在的情况，这两件事情互相之间本来既不充分也不必要，你自信按照充要进一步演绎出结论。我觉得一个计算机行业的人是这种逻辑能力水平，真是很让人吃惊的。总而言之，你对我的issue说了一些让人匪夷所思的话，想不明白你为什么突然攻击一个素不相识的人。可能你平时现实生活中就是这么说话的，那我当然无权干涉。我怎么看当然不重要，你怎么看也不重要，个人的看法都很微小，都没什么意义。筛选，那自然是双向筛选了。滥用，那就很高估我了，这脚本我根本都用不了，还滥用呢。打扰你开发，我非常抱歉，那你现在可以拉黑我了。

我就是没有能力分辨是不是有人滥用脚本，所以我会认为如果**连中文文档都读不懂**，连**编译好的程序都不知道怎么执行**的人**就不应该使用这个程序**。—— 你可能不明白这两个条件有多低，但是你刚好都中了。

你提的问题本身就有问题，如果你是按照我的步骤来做的，你根本不可能出现这个问题，你不可能发出这个issue。—— 在我的筛选规则里，你就不应该用这个程序。

> 对于你这个issue，我其实非常清楚你做了什么：你下载了源码，没有下载编译好的程序。你的问题过于啥b，与其指导你学会用这个程序，不如劝退你。 —— 我在文档特地强调了要下载的文件名，这都能下错？

至于“逃课”的说法，那是对本项目的补充说明，并不针对你，针对所有使用者，不要对号入座。

另外，你提到的：**你明明只能推断出我是你这脚本的一个使用者，其它方面信息都是不足的，你根本不认识我，不知道我是什么人，使用这脚本是派啥用场，你却就直接认定我是逃课的** 和 **可能你平时现实生活中就是这么说话的** 是不是有点双标了？我不解释，你逻辑能力那么好，应该看得懂哪里双标了吧。

不知道你能不能搞清楚发生了什么，我可以帮你总结下：
1. 本项目使用门槛非常低，只要你能**装上运行环境** + **从GitHub下载编译好的程序**就能开始用；
2. 你没能读懂文档；
3. 我知道你没读懂文档；
4. 我觉得你是啥b，我想劝退你；
5. 你觉得我是啥b，想教我做人；

别尝试教我做人了，你要有这个能力，怎么还读不懂文档呢。

**Comment by BrightMoonInner** [comment]
反正你就是非常有信心自己的程序和注释是没有问题的喽，就那么确信是我下错了？我都说了就是按照说明点的，NET下载是点击的你的链接，zip也是你提供的。这么两步操作你也不相信我能操作对是吧，建议你直接说我不识字也不认识电脑得了。我不识字，用ctrl c, v, f来定位需要下载的内容好不好？噢，还是不行，因为我是啥b。你的程序完美无瑕无懈可击，我说那就是我错。另外，那提法可不是双标昂，以其人之道还治其人之身罢了。劝退我，你死了这条心吧，我找到其它替代了，不劳你费心了。你认定我不是目标用户后，还帮我分析，那我真的是很感动呢。你是圣人啊，谁敢教你做人啊，你别害怕。总之呢，这正是印证我所说的，计算机行业的人自视甚高迷之自信，掌握了一定的技术之后就看不起普通群众，自觉高人一等，也是很常见了。大佬在用户群里狂怼萌新我也见的多了。用户提了一些问题，就觉得简单，嗤之以鼻不屑一顾，不愿回答，动辄厉声喝退乃至恶语相加，觉得自己开发设计辛苦极了，于是不可一世目中无人。噢，我也不是针对你，只说这个行业普遍现象，也请你不要对号入座。性格很刚，对线不想输？好的呢，是我输了哦，你取得了对刁民作战的全面胜利，后面不管你是乘胜追击还是懒得再追，我也不再回复，都是你对。

**Comment by moeshin** [comment]
emmm :sweat_smile:

从你的报错内容，确信你是下载错了，你想直接运行却下了源码。
因为编译也可能会出现类似错误，所以上次才那么回复。

------

当时你提问的时候，最新的提交是 3 月 3 号的 e3c0d7e

其中 `README.md` 并没有错误：

> ### 0x00 运行环境
> 
> 首先需要在 [.Net Runtime 下载页](https://dotnet.microsoft.com/download/dotnet/current/runtime) 下载并安装 **.NET5 Runtime**（提示：Run server apps下边的下载）。
> 
> 然后在 [Release页面](https://github.com/cyanray/cx-auto-sign/releases) 下载 cx-auto-sign.zip，并解压到某个目录。
> 
> （你也可以在 [Actions](https://github.com/cyanray/cx-auto-sign/actions) 中找到自动编译的测试版）

你下载的 zip，肯定是源码，而不是编译后的。
因为源码才有 `global.json` 文件。

从你的文件夹名 `cx-auto-sign-master` 还可以推断出你是点击 `Code` > `Download ZIP` 下载源码的。
可能是你经常使用 Python、JS 这些脚本而养成的习惯。
但 C# 是需要编译运行的。

有时间对线还不如多学点编程多读点书。

**Comment by cyanray** [comment]
> 反正你就是非常有信心自己的程序和注释是没有问题的喽，就那么确信是我下错了？我都说了就是按照说明点的，NET下载是点击的你的链接，zip也是你提供的。这么两步操作你也不相信我能操作对是吧，建议你直接说我不识字也不认识电脑得了。我不识字，用ctrl c, v, f来定位需要下载的内容好不好？噢，还是不行，因为我是啥b。你的程序完美无瑕无懈可击，我说那就是我错。另外，那提法可不是双标昂，以其人之道还治其人之身罢了。劝退我，你死了这条心吧，我找到其它替代了，不劳你费心了。你认定我不是目标用户后，还帮我分析，那我真的是很感动呢。你是圣人啊，谁敢教你做人啊，你别害怕。总之呢，这正是印证我所说的，计算机行业的人自视甚高迷之自信，掌握了一定的技术之后就看不起普通群众，自觉高人一等，也是很常见了。大佬在用户群里狂怼萌新我也见的多了。用户提了一些问题，就觉得简单，嗤之以鼻不屑一顾，不愿回答，动辄厉声喝退乃至恶语相加，觉得自己开发设计辛苦极了，于是不可一世目中无人。噢，我也不是针对你，只说这个行业普遍现象，也请你不要对号入座。性格很刚，对线不想输？好的呢，是我输了哦，你取得了对刁民作战的全面胜利，后面不管你是乘胜追击还是懒得再追，我也不再回复，都是你对。

哦

**Comment by BrightMoonInner** [comment]
> emmm 😅
> 
> 从你的报错内容，确信你是下载错了，你想直接运行却下了源码。 因为编译也可能会出现类似错误，所以上次才那么回复。
> 
> 当时你提问的时候，最新的提交是 3 月 3 号的 [e3c0d7e](https://github.com/cyanray/cx-auto-sign/commit/e3c0d7e479a558b215ffdc74d9d7dd659a94f10d)
> 
> 其中 `README.md` 并没有错误：
> 
> > ### 0x00 运行环境
> > 首先需要在 [.Net Runtime 下载页](https://dotnet.microsoft.com/download/dotnet/current/runtime) 下载并安装 **.NET5 Runtime**（提示：Run server apps下边的下载）。
> > 然后在 [Release页面](https://github.com/cyanray/cx-auto-sign/releases) 下载 cx-auto-sign.zip，并解压到某个目录。
> > （你也可以在 [Actions](https://github.com/cyanray/cx-auto-sign/actions) 中找到自动编译的测试版）
> 
> 你下载的 zip，肯定是源码，而不是编译后的。 因为源码才有 `global.json` 文件。
> 
> 从你的文件夹名 `cx-auto-sign-master` 还可以推断出你是点击 `Code` > `Download ZIP` 下载源码的。 可能是你经常使用 Python、JS 这些脚本而养成的习惯。 但 C# 是需要编译运行的。
> 
> 有时间对线还不如多学点编程多读点书。

谢谢大佬，比较抱歉让你见到这种很不好的事情。我也没有想到会这样，因为本来我确实就是过来咨询问题的，我觉得我也很客气，态度也没有问题，没想到你的这位朋友不知道怎么的就夹枪带棒讥讽我是逃课选手……一堆奇奇怪怪的说辞。我就很反感，希冀他能把这种没来由的话说清楚。后来这个勉强说清楚了，他又跟我讲什么滥用，哎，话说你既然都觉得我蠢笨而使用不了这个程序，那又哪来的滥用呢对吧。总之这逻辑我就觉着离谱。忍不住就多说了一些。你不帮忙解决问题倒没有什么，但你还要无缘无故说些膈应人的话就很过分了吧。计算机行业的人多心高气傲，这个话不是我说的，我引用了下，向被误伤的人道歉。再次向大佬道歉，烦请大佬转告你这位朋友我向他道歉，人吧不是坏人，说话是真的相当难听，同样的意思能用最令人反感的方式表达出来……好了，读书了，不打扰你们了。
